# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: Website of Brandon Sheffield - mastash3ff
name: mastash3ff's website
email: brandon@sheffconsulting.com

description: > #Another place on the internet for how-tos aimed at sharing
  information about open source development and tools.

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://sheffconsulting.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: bsheffield2008
github_username:  mastash3ff

defaults:
 - scope:
          path: ""
          type: "posts"
   values:
          layout: "post"

version: "1.0.3"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

include: ['_pages']

# Third-party services
disqus_shortname:
ga_analytics: #insert google analytics here

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->


