# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Website of Brandon Sheffield - mastash3ff 
name: mastash3ff's website
email: brandon@bsheffield.com
description: > #Another place on the internet for how-tos aimed at sharing
  information about open source development and tools.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bsheffield.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: bshefield2008
github_username:  mastash3ff

defaults:
 - scope:
          path: ""
          type: "posts"
   values:
          layout: "post"

version: "1.0.3"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

paginate: 8
paginate_path: /page:num/

include: ['_pages']

ga_analytics: #insert google analytics here


